# Generated by Django 5.1.4 on 2025-02-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_placedstudent_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedstudent',
            name='photo',
            field=models.ImageField(upload_to='students/'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
