# Generated by Django 5.1.4 on 2025-03-03 04:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_alter_placedstudent_photo_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='photo',
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='placement_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='role',
            field=models.CharField(default='Unknown Role', max_length=255),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='placedstudent',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placedstudent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.company'),
        ),
    ]
