# Generated by Django 5.1.7 on 2025-03-24 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_company_remove_placedstudent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='placedstudent',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_percent', models.FloatField(blank=True, null=True)),
                ('twelfth_percent', models.FloatField(blank=True, null=True)),
                ('graduation_percent', models.FloatField(blank=True, null=True)),
                ('placement_status', models.CharField(choices=[('Placed', 'Placed'), ('Unplaced', 'Unplaced'), ('In Progress', 'In Progress')], default='Unplaced', max_length=20)),
                ('package', models.FloatField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='PlacedStudent',
        ),
    ]
