# Generated by Django 5.1.7 on 2025-03-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_batch_remove_placedstudent_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='package',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placements.batch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='tenth_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='twelfth_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
